### ISSUE TITLE
dashicons stylesheet not enqueued

### ISSUE THREAD

**Issue by dotsam** [threadi/downloadlist#100]
I only noticed this when logged out (as dashicons is loaded when logged in), but the dashicons stylesheet is not enqueued after 6b024cb, as it's trying to enqueue `downloadlist-dashicons`, which doesn't exist.

As a workaround, I've set up that handle as an alias of dashicons:
```
wp_register_style('downloadlist-dashicons', false, ['dashicons']);
```

**Comment by threadi** [comment]
Thanks for the hint and the solution. I managed to solve this in #101 and it will be in the next release.
